source_user:
  # 基本账号信息
  id: 1000012631
  username: autotest_dev1
  email: autotest_dev1@qq.com
  password: m1234567
  sprite:
    owned: 34    # 草灵灵
    unown: 1     # 编程猫
 
target_user:
  id: 1000002872
  username: autotest_dev2
  password: m1234567
  # 用户未设置本命精灵：user_extension.familiar_sprite为Null或0