source_user:
  id: 1000002450
  username: mxq111
  password: m1234567
  work:
    ide:
      published_work_id: 2675933
      unpublish_work_id: 2675934
      deleted_temporarily_work_id: 2675935
      deleted_permanently_work_id: 2675938
    wood:
      work_id: 2676059
    nemo:
      work_id: 2674264
  sprite:
    owned: 50    # 象牙螺
    unown: 1     # 编程猫
target_user:
  id: 1000002872
  username: mxq121
  password: m1234567
  work:
    ide:
      published_work_id: 2675915
      published_unfork_work_id: 2676251
      unpublish_work_id: 2676253
      deleted_temporarily_work_id: 2676255
      deleted_permanently_work_id: 2676257
