source_user:
  id: 1000002450
  username: mxq111
  password: m1234567
  work:
    ide:
      published_work_id: 2675933
      unpublish_work_id: 2675934
      deleted_temporarily_work_id: 2675935
      deleted_permanently_work_id: 2675938
      # 用于测试创建作品/修改作品/修改作品封面，bcm文件实际上就是经过处理的json字符串
      # work_url未加密，bcmc_url有加密(可选)，作品播放内容根据bcmc_url展示
      work_url: https://test.bcmcdn.com/kitten/ByW-83V1N.bcm
      preview_url: https://test.bcmcdn.com/kitten/SkbbU3E1N
      bcmc_url: https://test.bcmcdn.com/kitten/SkMW83VyV.bcmc
    boxv1:
      work_url: https://static.codemao.cn/a550635c-c592-49f6-a0ec-7febd50a2a60.bcm
      preview_url: https://preview.codemao.cn/FtjU5vGuYhkXIv37QUcQ-DMJbSch
    # 为了避免产生脏数据导致打开作品时报错，所以work_url必须是同类型url
    boxv2:
      work_url: https://test.bcmcdn.com/box/H1Ljb3EyE.bcm
      preview_url: https://obxuuymk6.qnssl.com/default_preview.png
      bcmc_url: https://test.bcmcdn.com/box/rJUiZhN1E.bcmc
    wood:
      # 未发布
      work_id: 2676059
    nemo:
      work_id: 2674264
      work_url: https://test.bcmcdn.com/nemo/HJq-zvZpX.bcm
      preview_url: https://test.bcmcdn.com/nemo/Bk9-MD-pQ.cover
  sprite:
    owned: 50    # 象牙螺
    unown: 1     # 编程猫

target_user:
  id: 1000002872
  username: mxq121
  password: m1234567
  work:
    ide:
      published_work_id: 2675915  
      published_unfork_work_id: 2676251
      unpublish_work_id: 2676253
      deleted_temporarily_work_id: 2676255
      deleted_permanently_work_id: 2676257
    nemo:
      work_id: 2678946
