# 账号北森uid不为0
fish_account_beisen:
    fish_id: 639
    username: maxiaoqian
    password: m1234567
    encrypted_password: Ma123456
    email: maxiaoqian@codemao.cn

# 账号北森uid为0
fish_account_without_beisen:
    fish_id: 109
    username: yaolitest
    password: m1234567
    encrypted_password: ''