mysql:
  account:
    host: rm-bp173j25673ah67z8ko.mysql.rds.aliyuncs.com
    user: TestDep
    password: 4Ehp1ndpfnlN9D0qvg4SZuig
    database: account
redis:
  # 需要开启VPN
  host: r-bp19c78721368bd4371.redis.rds.aliyuncs.com
  port: 6379
  password: liuWcl8hj3InVQONzonkIeNa