mysql:
  account:
    host: ""
    user: ""
    password: ""
    database: account
  internal_account:
    host: ""
    user: ""
    password: ""
    database: internal_account
    
redis:
  host: ""
  port: 6379
  password: ""