mysql:
  host: rm-bp15t47j196je1u0l4o.mysql.rds.aliyuncs.com
  user: TestDep
  password: 4Ehp1ndpfnlN9D0qvg4SZuig
redis:
  # 需要开启VPN
  host: r-bp1a97853b5914d4.redis.rds.aliyuncs.com
  port: 6379
  password: HjKxGkp3jbWbxGgQzSrKBBc6