mysql:
  account:
    host: rm-bp1orqjl80dle29ur878.mysql.rds.aliyuncs.com
    user: maxiaoqian
    password: gB3h0VWWy8dpJAdhPkFsCeTj
    database: account
  internal_account:
    host: rm-bp1orqjl80dle29ur878.mysql.rds.aliyuncs.com
    user: huhong
    password: WFk6B9FHA2alCOma6Aouhwtcdy4ZOOkr
    database: internal_account

redis:
  host: r-bp1a97853b5914d4289.redis.rds.aliyuncs.com
  port: 6379
  password: 1dVIrGV24PcgOELF5rNphq1L